# A minimal stand-in for pandoc's output: `split_readme()` reads it back from
# disk, so the tests write it there and call the post-processing step directly.
local_readme <- function(lines, env = parent.frame()) {
  root <- withr::local_tempdir(.local_envir = env)
  writeLines(lines, file.path(root, "README.md"))
  root
}

buildignore <- function(root) {
  path <- file.path(root, ".Rbuildignore")
  if (!file.exists(path)) character() else readLines(path, warn = FALSE)
}

test_that("a differing front page is written, marked and build-ignored", {
  root <- local_readme(c("# Title", "", "Body.", "", strrep("-", 72), "", "Tail."))

  split_readme(root, file.path(root, "README.md"))

  index <- readLines(file.path(root, "index.md"), warn = FALSE)
  expect_match(index[[1]], "^<!-- Generated by cynkratemplate")
  expect_equal(index[-1], c("# Title", "", "Body."))
  expect_true("^index\\.md$" %in% buildignore(root))
})

test_that("a generated index.md that is no longer needed is removed", {
  root <- local_readme(c("# Title", "", "Body."))
  # What a previous render, back when the README still had a rule, left behind.
  writeLines(
    c("<!-- Generated by cynkratemplate: do not edit by hand -->", "# Title"),
    file.path(root, "index.md")
  )
  writeLines("^index\\.md$", file.path(root, ".Rbuildignore"))

  expect_silent(split_readme(root, file.path(root, "README.md")))

  expect_false(file.exists(file.path(root, "index.md")))
  expect_false("^index\\.md$" %in% buildignore(root))
})

test_that("a hand-written index.md is kept, with a warning", {
  root <- local_readme(c("# Title", "", "Body."))
  hand <- c("# A front page of my own", "", "Written by hand.")
  writeLines(hand, file.path(root, "index.md"))

  expect_warning(
    split_readme(root, file.path(root, "README.md")),
    "did not produce it"
  )

  expect_equal(readLines(file.path(root, "index.md"), warn = FALSE), hand)
  # The file is still there, so it still has to be ignored by `R CMD build`.
  expect_true("^index\\.md$" %in% buildignore(root))
})

test_that("no index.md and none needed leaves nothing behind", {
  root <- local_readme(c("# Title", "", "Body."))

  expect_silent(split_readme(root, file.path(root, "README.md")))

  expect_false(file.exists(file.path(root, "index.md")))
  expect_false("^index\\.md$" %in% buildignore(root))
})

test_that("the marker does not decide whether the two files differ", {
  # The head equals the whole README here, so the only difference the marker
  # could introduce is the marker itself. It must not count.
  root <- local_readme(c("# Title", "", "Body."))
  writeLines(
    c("<!-- Generated by cynkratemplate: do not edit by hand -->", "# Title"),
    file.path(root, "index.md")
  )

  split_readme(root, file.path(root, "README.md"))

  expect_false(file.exists(file.path(root, "index.md")))
})

test_that("a marked index.md is refreshed in place", {
  root <- local_readme(c("# Title", "", "New body.", "", strrep("-", 72), "", "Tail."))
  writeLines(
    c("<!-- Generated by cynkratemplate: do not edit by hand -->", "# Title", "", "Old body."),
    file.path(root, "index.md")
  )

  expect_silent(split_readme(root, file.path(root, "README.md")))

  index <- readLines(file.path(root, "index.md"), warn = FALSE)
  expect_equal(index[-1], c("# Title", "", "New body."))
})
